In [1]:
from pyincore import IncoreClient
from pyincore.analyses.mlenabledcgegalveston import MlEnabledCgeGalveston
from pyincore import globals as pyglobals

# Supress default INFO logging

import logging

logger = pyglobals.LOGGER
logger.setLevel(logging.CRITICAL)

In [3]:
client = IncoreClient()

Connection successful to IN-CORE services. pyIncore version detected: 1.20.1

In [2]:
sector_shocks = "643adeb634810d74880e7bd5"  # This is the aggregation of building functionality states to capital shocks per sector.

In [4]:
# Create Machine Learning Enabled CGE Salt Lake City Model
ml_enabled_cge = MlEnabledCgeGalveston(client)

In [5]:
# Set analysis input datasets
ml_enabled_cge.load_remote_input_dataset("sector_shocks", sector_shocks)

# Optional parameters for file naming
ml_enabled_cge.set_parameter("result_name", "test_galveston_mlcge_result")

True

In [6]:
# Run Galveston city CGE model analysis
ml_enabled_cge.run_analysis()

True

In [7]:
domestic_supply = ml_enabled_cge.get_output_dataset("domestic-supply")
ds = domestic_supply.get_dataframe_from_csv()
# Display top 6 rows of output data
ds.head(6)

   Sectors         DS0         DSL
0   IAGMIN   26.064448   25.401881
1    IUTIL   84.813701   81.456728
2    ICONS  291.795770  268.448117
3    IMANU  440.355302  425.729920
4   IWHOLE   64.653385   58.659894
5  IRETAIL  356.863762  300.725250

In [8]:
gross_income = ml_enabled_cge.get_output_dataset("gross-income")
gi = gross_income.get_dataframe_from_csv()
gi.head()

  Household Group          Y0          YL
0           HH1WI    4.182551    4.025747
1           HH2WI   27.755117   25.159567
2           HH3WI  132.402541  119.902432
3           HH4WI  528.592326  467.634796
4           HH5WI  661.228690  551.756431

In [9]:
pre_factor_demand = ml_enabled_cge.get_output_dataset("pre-disaster-factor-demand")
pre_fd = pre_factor_demand.get_dataframe_from_csv()
pre_fd.head()

  Labor Group  IAGMIN_WI  IAGMIN_BI  ...  MREALE_BM  MART_BM  MAGMIN_BM
0          L1        7.0        4.0  ...       -1.0     -1.0       17.0
1          L2       -1.0       -1.0  ...       87.0     98.0       -1.0
2          L3       39.0       -1.0  ...       -1.0     -1.0       -1.0
3          L4       49.0        7.0  ...       -1.0     -1.0       32.0

[4 rows x 97 columns]

In [10]:
post_factor_demand = ml_enabled_cge.get_output_dataset("post-disaster-factor-demand")
pos_fd = post_factor_demand.get_dataframe_from_csv()
pos_fd.head()

  Labor Group  IAGMIN_WI  IAGMIN_BI  ...  MREALE_BM  MART_BM  MAGMIN_BM
0          L1   6.919477   3.954415  ...       -1.0     -1.0       17.0
1          L2  -1.000000  -1.000000  ...       87.0     98.0       -1.0
2          L3  38.204932  -1.000000  ...       -1.0     -1.0       -1.0
3          L4  48.072902   6.844827  ...       -1.0     -1.0       32.0

[4 rows x 97 columns]

In [11]:
household_count = ml_enabled_cge.get_output_dataset("household-count")
hc = household_count.get_dataframe_from_csv()
hc.head()

  Household Group     HH0          HHL
0           HH1WI   655.0   650.860310
1           HH2WI  1195.0  1182.226953
2           HH3WI  2618.0  2585.294201
3           HH4WI  4114.0  4044.787173
4           HH5WI  3321.0  3216.563992